# ⚠️⚠️⚠️ Check autoupdater.py! Seriously! ⚠️⚠️⚠️

name: aeiea/autoupdateonfolder-workflow
description: automatically update a file(which contains a list of filenames) upon changes are made to a folder
author: aeiea
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Updating files
        env: 
          API_KEY: ${{ secrets.GH_TOKEN }}
        run: |
          echo Updating Files...
          python .github/workflows/autoupdater.py
          echo Done!
      - name: Commit and push changes
        run: |
          git config --global user.name "aeiea"
          git config --global user.email "dpthn@proton.me"
          git add -A
          git commit -m "update list"
          git push
