# ⚠️⚠️⚠️ Check autoupdater.py! Seriously! ⚠️⚠️⚠️

name: aeiea/autoupdateonfolder-workflow
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - name: Updating files
        env: 
          API_KEY: ${{ secrets.GH_TOKEN }}
        run: |
          echo Updating Files...
          python /.github/workflows/autoupdater.py
          echo Done!
